# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            puerapuliae
tagline:          The Jekyll Butler
url:              http://puerapuliae.net
paginate:         1
baseurl:          /
author:
  name:           Björn Klatt

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/puerapuliae/puerapuliae

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
